"""update answer table column name

Revision ID: 8f8cfaf32419
Revises: f953e74892ca
Create Date: 2022-06-12 10:11:06.156825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8cfaf32419'
down_revision = 'f953e74892ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('answers', 'answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('answers', 'content')
    # ### end Alembic commands ###
